### ISSUE TITLE
Voting on sample polls

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/xoopspoll#5]
When I vote on the existing sample surveys (/modules/xoopspoll/index.php), I get this error:
Error: TypeError: XoopsModules/Xoopspoll/PollHandler::updateCount(): Return value must be of type bool, int returned in file /modules/xoopspoll/class/PollHandler.php line 65

___

My config (all in english):
Xoops 2.5.11-Beta2
XoopsPoll 2.1.0 Beta 1
PHP 8.1.2-1ubuntu2.9
MYSQL 8.0.31-0ubuntu0.22.04.1

**Comment by mambax7** [comment]
I've added some fixes - could you test it with the latest code?

**Comment by cesagonchu** [comment]
Solved, thank you very much!
