### ISSUE TITLE
Comment on a survey

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/xoopspoll#6]
When I post a comment on a survey, I get this error:
Warning: Undefined array key "image" in file /xdata/xoops_dataxxx/caches/smarty_compile/f9c52d55-xoopspoll-default-default^%%5E^5EF^5EF52765%%db%3Asystem_comment.tpl.php line 52

___

My config (all in english):
Xoops 2.5.11-Beta2
XoopsPoll 2.1.0 Beta 1
PHP 8.1.2-1ubuntu2.9
MYSQL 8.0.31-0ubuntu0.22.04.1

**Comment by mambax7** [comment]
What theme do you use?

**Comment by cesagonchu** [comment]
Default theme

**Comment by mambax7** [comment]
You can ignore it. 
But if you want to get rid of it, try to change line 32 in \modules\system\templates\system_comment.tpl
from 
```html <div class="comTitle"><{$comment.image}><{$comment.title}></div>```

to:

```html <div class="comTitle"><{$comment.image|default:''}><{$comment.title}></div> ```

and let me know if it helped.

**Comment by cesagonchu** [comment]
Yes, thank you, that solved the problem!  One of our users is using the default Xoops theme. Can you make this correction to the core?

**Comment by mambax7** [comment]
I will submit it, but please open a new issue over there, and once you do, please close it here.
