### ISSUE TITLE
Adding a poll

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/xoopspoll#7]
When I want to add a survey, on the administration side (/modules/xoopspoll/admin/main.php?op=add), I get this error:
Error: TypeError: XoopsModules/Xoopspoll/OptionHandler::renderOptionFormTray(): Argument #1 ($pid) must be of type int, null given, called in /modules/xoopspoll/class/Poll.php on line 315 in file /modules/xoopspoll/class/OptionHandler.php line 155

___

My config (all in english):
Xoops 2.5.11-Beta2
XoopsPoll 2.1.0 Beta 1
PHP 8.1.2-1ubuntu2.9
MYSQL 8.0.31-0ubuntu0.22.04.1

**Comment by mambax7** [comment]
I've added some fixes - could you test it with the latest code?

**Comment by cesagonchu** [comment]
Thank you. I was able to create a poll, but when I wanted to vote, I got this error:

Error: TypeError: XoopsModules/Xoopspoll/Poll::vote(): Argument #1 ($optionId) must be of type int, array given, called in /modules/xoopspoll/index.php on line 194 in file /modules/xoopspoll/class/Poll.php line 135

**Comment by mambax7** [comment]
I hope, this commit will fix it. Please test it and let me know. 
https://github.com/mambax7/xoopspoll/commit/9b414c2c60ff637be0cb71c65dfd4a16b32e56ab

**Comment by cesagonchu** [comment]
Yes it works, thank you!
