### ISSUE TITLE
blocksadmin

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/xoopspoll#8]
When I go to the "blockadmin" tab (/modules/xoopspoll/admin/blocksadmin.php) on the admin side and check "yes" to make the poll blocks visible, I get this error:
Error: TypeError: XoopsModules/Xoopspoll/Poll::getComments(): Return value must be of type int, string returned in file /modules/xoopspoll/class/Poll.php line 198

___

My config (all in english):
Xoops 2.5.11-Beta2
XoopsPoll 2.1.0 Beta 1
PHP 8.1.2-1ubuntu2.9
MYSQL 8.0.31-0ubuntu0.22.04.1

**Comment by mambax7** [comment]
Can you check if you have the latest XOOPS file https://github.com/XOOPS/XoopsCore25/blob/master/htdocs/kernel/comment.php ?

The function  ```getCount()``` there should return Integer (line 521), and that's what the function ```getComments()``` in Poll class expects (line 196):

```php
    public function getComments(): int
    {
        $moduleHandler = \xoops_getHandler('module');
        $pollModule    = $moduleHandler->getByDirname('xoopspoll');

        /** @var \XoopsCommentHandler $commentHandler */
        $commentHandler = \xoops_getHandler('comment');
        $criteria       = new \CriteriaCompo();
        $criteria->add(new \Criteria('com_itemid', $this->getVar('poll_id'), '='));
        $criteria->add(new \Criteria('com_modid', $pollModule->getVar('mid'), '='));
        $commentCount = $commentHandler->getCount($criteria); //<= this line

        return $commentCount;
    }
```

**Comment by cesagonchu** [comment]
Oh no I don't have the latest Xoops core on my dedicated server :p I will install it in a few days.

**Comment by cesagonchu** [comment]
With latest Xoops version it's ok, no error messages. 
Therefore, can you modify the Xoops version requirement to install the XoopsPoll module?
**"Minimum XOOPS required: 2.5.11"** instead of "Minimum XOOPS required: 2.5.10"

**Comment by mambax7** [comment]
Done
