### ISSUE TITLE
Default theme error with Poll comments

### ISSUE THREAD

**Issue by cesagonchu** [mambax7/xoopspoll#9]
Using the default Xoops theme, when I write a comment on a poll (/modules/xoopspoll/pollresults.php?poll_id=1&com_id=1&com_rootid=1&com_mode=flat&com_order=0#comment1), I get this error:

> Warning: Undefined array key "image" in file /xoops_dataxx/caches/smarty_compile/6e4a5552-xoopspoll-default-default^%%5E^5EF^5EF52765%%db%3Asystem_comment.tpl.php line 52

___

My config

PHP version 8.1.2-1ubuntu2.10
MYSQL 8.0.32-0ubuntu0.22.04.2
XoopsPoll 2.1.0 Beta 1 (Mamba version)
XOOPS 2.5.11-Beta2 (latest version)

**Comment by mambax7** [comment]
It should be fixed in the latest code
